spring:
  application:
  name: myselectshop

  datasource:
  url: jdbc:mysql://localhost:3306/shop
  username: root
  password: 1234
  driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
    show_sql: true
    format_sql: true
    use_sql_comments: true

#  datasource:
#    url: jdbc:h2:mem:shop
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#  console: enabled=true

jwt:
  secret:
    key: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="

kakao:
  rest-api-key: "c2aa578f21769dacdc16cb81facad842"
